// Realistic book listings for development and demo
// These will be assigned to users during seeding
export const booksData = [
  {
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen, Charles E. Leiserson",
    isbn: "9780262033848",
    courseCode: "CS 374",
    condition: "new",
    price: 89.99,
    description: "Third edition, barely used. All pages intact, no highlighting.",
    status: "available",
  },
  {
    title: "Data Structures and Algorithm Analysis in C++",
    author: "Mark Allen Weiss",
    isbn: "9780132847377",
    courseCode: "CS 225",
    condition: "used",
    price: 45.00,
    description: "Some highlighting in first few chapters. Great condition otherwise.",
    status: "available",
  },
  {
    title: "Computer Organization and Design",
    author: "David A. Patterson, John L. Hennessy",
    isbn: "9780124077263",
    courseCode: "CS 233",
    condition: "used",
    price: 35.50,
    description: "Used for one semester. Cover has some wear but all pages are readable.",
    status: "available",
  },
  {
    title: "Operating System Concepts",
    author: "Abraham Silberschatz",
    isbn: "9781119320913",
    courseCode: "CS 341",
    condition: "new",
    price: 95.00,
    description: "10th edition, mint condition. Bought but never really used it.",
    status: "available",
  },
  {
    title: "Artificial Intelligence: A Modern Approach",
    author: "Stuart Russell, Peter Norvig",
    isbn: "9780136042594",
    courseCode: "CS 440",
    condition: "used",
    price: 78.00,
    description: "3rd edition. Some notes in margins. Great reference book.",
    status: "available",
  },
  {
    title: "Database System Concepts",
    author: "Abraham Silberschatz, Henry F. Korth",
    isbn: "9780078022159",
    courseCode: "CS 411",
    condition: "used",
    price: 25.00,
    description: "7th edition. Heavy use but all content is there. Good for budget.",
    status: "available",
  },
  {
    title: "Computer Networks",
    author: "Andrew S. Tanenbaum, David J. Wetherall",
    isbn: "9780132126953",
    courseCode: "CS 423",
    condition: "used",
    price: 55.00,
    description: "5th edition. Clean copy with minimal wear.",
    status: "available",
  },
  {
    title: "Compilers: Principles, Techniques, and Tools",
    author: "Alfred V. Aho, Monica S. Lam",
    isbn: "9780321486813",
    courseCode: "CS 426",
    condition: "new",
    price: 85.00,
    description: "The Dragon Book! Second edition, excellent condition.",
    status: "available",
  },
  {
    title: "Introduction to the Theory of Computation",
    author: "Michael Sipser",
    isbn: "9781133187790",
    courseCode: "CS 374",
    condition: "used",
    price: 52.00,
    description: "3rd edition. Some highlighting but overall good shape.",
    status: "available",
  },
  {
    title: "Discrete Mathematics and Its Applications",
    author: "Kenneth H. Rosen",
    isbn: "9780073383095",
    courseCode: "CS 173",
    condition: "used",
    price: 30.00,
    description: "7th edition. Lots of pencil notes and highlighting. Still usable.",
    status: "available",
  },
  {
    title: "The C Programming Language",
    author: "Brian W. Kernighan, Dennis M. Ritchie",
    isbn: "9780131103627",
    courseCode: "CS 241",
    condition: "used",
    price: 28.00,
    description: "Classic K&R book. 2nd edition, well-maintained.",
    status: "available",
  },
  {
    title: "Computer Graphics: Principles and Practice",
    author: "John F. Hughes, Andries van Dam",
    isbn: "9780321399526",
    courseCode: "CS 418",
    condition: "new",
    price: 92.00,
    description: "3rd edition. Only used for reference, like new.",
    status: "available",
  },
  {
    title: "Fluent React",
    author: "Tejas Kumar",
    isbn: "9781098138714",
    courseCode: "CS 409",
    term: "Fall 2025",
    condition: "used",
    price: 15.00,
    description: "Build fast, performant, and intuitive web applications.",
    status: "available",
    ownerEmail: "jane.doe@illinois.edu",
  },
  {
    title: "Business Analytics",
    author: "James R. Evans",
    isbn: "9780135231678",
    courseCode: "BUS 456",
    term: "Spring 2026",
    condition: "used",
    price: 32.00,
    description: "3rd edition. Good for learning business analytics fundamentals.",
    status: "available",
  },
  {
    title: "Macroeconomics",
    author: "N. Gregory Mankiw",
    isbn: "9781319105990",
    courseCode: "ECON 233",
    term: "Winter 2025",
    condition: "used",
    price: 50.00,
    description: "Great condition. All pages clean and readable.",
    status: "available",
  },
];
