export const ratingsData = [
  {
    raterEmail: "alex.smith@illinois.edu",
    rateeEmail: "jane.doe@illinois.edu",
    requestIndex: 1,
    score: 5,
    comment: "Great seller! Book was in perfect condition as described. Quick meetup and very friendly.",
  },
  {
    raterEmail: "emily.chen@illinois.edu",
    rateeEmail: "jane.doe@illinois.edu",
    requestIndex: 2,
    score: 5,
    comment: "Excellent transaction! Book arrived exactly as described and the price was fair.",
  },
  {
    raterEmail: "john.doe@illinois.edu",
    rateeEmail: "alex.smith@illinois.edu",
    requestIndex: 3,
    score: 4,
    comment: "Good experience overall. Book had a bit more wear than expected but still usable.",
  },
  {
    raterEmail: "jane.doe@illinois.edu",
    rateeEmail: "mike.johnson@illinois.edu",
    requestIndex: 4,
    score: 5,
    comment: "Amazing! Met at the union as planned. Book was in mint condition. Highly recommend!",
  },
  {
    raterEmail: "emily.chen@illinois.edu",
    rateeEmail: "alex.smith@illinois.edu",
    requestIndex: 5,
    score: 5,
    comment: "Perfect! Great price and the book quality exceeded my expectations.",
  },
  {
    raterEmail: "mike.johnson@illinois.edu",
    rateeEmail: "emily.chen@illinois.edu",
    requestIndex: 6,
    score: 4,
    comment: "Good seller. Book had some notes but they were actually helpful for understanding the material.",
  },
  {
    raterEmail: "alex.smith@illinois.edu",
    rateeEmail: "john.doe@illinois.edu",
    requestIndex: 7,
    score: 5,
    comment: "Fantastic! Very responsive and accommodating with meeting time. Book in great shape.",
  },
  {
    raterEmail: "jane.doe@illinois.edu",
    rateeEmail: "emily.chen@illinois.edu",
    requestIndex: 8,
    score: 4,
    comment: "Nice transaction. The book had more highlighting than I prefer but overall satisfied.",
  },
  {
    raterEmail: "mike.johnson@illinois.edu",
    rateeEmail: "john.doe@illinois.edu",
    requestIndex: 9,
    score: 5,
    comment: "Excellent seller! Book was the latest edition as promised. Very helpful and friendly.",
  },
  {
    raterEmail: "john.doe@illinois.edu",
    rateeEmail: "emily.chen@illinois.edu",
    requestIndex: 10,
    score: 5,
    comment: "Perfect timing! Needed it for my midterm and the seller met me within hours. Book in great condition!",
  },
];
